live_config_reload = true
working_directory = "None"

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xfd971f"
index = 16

[[colors.indexed_colors]]
color = "0xcc6633"
index = 17

[[colors.indexed_colors]]
color = "0x383830"
index = 18

[[colors.indexed_colors]]
color = "0x49483e"
index = 19

[[colors.indexed_colors]]
color = "0xa59f85"
index = 20

[[colors.indexed_colors]]
color = "0xf5f4f1"
index = 21

[colors.bright]
black = "0x75715e"
blue = "0x66d9ef"
cyan = "0xa1efe4"
green = "0xa6e22e"
magenta = "0xae81ff"
red = "0xf92672"
white = "0xf9f8f5"
yellow = "0xf4bf75"

[colors.cursor]
cursor = "0xf8f8f2"
text = "0x272822"

[colors.normal]
black = "0x272822"
blue = "0x66d9ef"
cyan = "0xa1efe4"
green = "0xa6e22e"
magenta = "0xae81ff"
red = "0xf92672"
white = "0xf8f8f2"
yellow = "0xf4bf75"

[colors.primary]
background = "0x272822"
foreground = "0xf8f8f2"

[colors.selection]
background = "0x404040"
text = "0xeaeaea"

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"
blinking = "On"

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

#[mouse.double_click]
#threshold = 300

#[mouse.triple_click]
#threshold = 300

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["--login"]
program = "/bin/bash"

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
